export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_BUY_ORDERS_SUCCESS = 'FETCH_BUY_ORDERS_SUCCESS';
export const FETCH_SELL_ORDERS_SUCCESS = 'FETCH_SELL_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';
export const FETCH_ORDER_HISTORY = 'FETCH_ORDER_HISTORY';
export const CREATE_NEW_ORDER = 'CREATE_NEW_ORDER';
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const EDIT_ORDER = 'EDIT_ORDER';